services:
  reverse-proxy:
    image: traefik:latest
    security_opt:
      - no-new-privileges:true
    ports:
      - "${TRAEFIK_PORT}:80"
      - "${TRAEFIK_SECURE_PORT}:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - ./traefik_dynamic.yml:/etc/traefik/traefik_dynamic.yml:ro
      - ./data/auth/users:/data/auth/users
      - ./data/logs/access.log:/data/logs/access.log
      - ./data/logs/traefik.log:/data/logs/traefik.log
      - ./certs:/etc/certs:ro
    environment:
      - TRAEFIK_DOMAIN
      - TRAEFIK_USER
    networks:
      - proxy
    logging:
      options:
        max-size: "10m"
        max-file: "3"

networks:
  proxy:
    external: true
    name: proxy